package summative_assessment;

public class StockItem {
    String name;
    int price;
    String manufacturer;
    String productID;
    int numberInStock;

    //constructor generated by IDE

    public StockItem(String name, int price, String manufacturer, String productID, int numberInStock) {
        this.name = name;
        this.price = price;
        this.manufacturer = manufacturer;
        this.productID = productID;
        this.numberInStock = numberInStock;
    }
}

