package summative_assessment;

public class StockItem {
    int price;
    String manufacturer;
    String productID;
    int numberInStock;

    //constructor generated by IDE
    public StockItem(int price, String manufacturer, String productID, int numberInStock) {
        this.price = price;
        this.manufacturer = manufacturer;
        this.productID = productID;
        this.numberInStock = numberInStock;
    }
}

