package models;

public class StockItem {
    public String name; // need to set access modifier to public here, otherwise they cannot be accessed in other classes
    public int price;
    public String manufacturer;
    public String productID;
    public int numberInStock;

    //constructor generated by IDE

    public StockItem(String name, int price, String manufacturer, String productID, int numberInStock) {
        this.name = name;
        this.price = price;
        this.manufacturer = manufacturer;
        this.productID = productID;
        this.numberInStock = numberInStock;
    }
}

